name: Android Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. إعداد الجافا (هذا الجزء اللي كان ناقصك ويسبب الخطأ)
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 2. إعداد Node.js 22
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --force

      - name: Build Web Project
        run: npm run build

      - name: Sync Capacitor to Android
        run: npx cap sync android

      - name: Give Permission
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Echo-App-Debug
          path: android/app/build/outputs/apk/debug/app-debug.apk